# vim ft=yaml
# travis-ci.org definition for stl_tools build
#

language: python
env:
    - PYTHON=python PYSUF='' PYVER=2.7
    - PYTHON=python3 PYSUF='3' PYVER=3.2
python:
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - sudo apt-get update  # needed for python3-numpy
  - sudo apt-get install $PYTHON-dev
  - sudo apt-get install $PYTHON-numpy
  - sudo apt-get install $PYTHON-scipy
  - sudo apt-get install $PYTHON-setuptools
  - sudo apt-get install $PYTHON-nose
  - "sudo python setup.py build install"
# command to run tests
script: nosetests
