# vim ft=yaml
# travis-ci.org definition for stl_tools build
#

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "sudo python setup.py build install"
# command to run tests
script: nosetests
